[[spirv2clc]]
arch = "aarch64"
git-tree-sha1 = "491886db33f7c24ace7f51ab7e8db0345aaa21d1"
os = "macos"

    [[spirv2clc.download]]
    sha256 = "0d476ed7106520c98d723c1f33762a9f7b7833bba6f876af74bb778ed8a47cf7"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.aarch64-apple-darwin.tar.gz"
[[spirv2clc]]
arch = "aarch64"
git-tree-sha1 = "67c05741502dcec8882170f70eb69a6897e53180"
libc = "glibc"
os = "linux"

    [[spirv2clc.download]]
    sha256 = "6af1460abd900019b9e3ff92c086a5b3cac653516dab93790f4042e62fa789c5"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.aarch64-linux-gnu.tar.gz"
[[spirv2clc]]
arch = "aarch64"
git-tree-sha1 = "dee07dc01884cddf5278e712c4fc185f02fc640c"
libc = "musl"
os = "linux"

    [[spirv2clc.download]]
    sha256 = "98627493f446072e13e04a2b431eb86bac9e1ec96411d90e4cd9a90138d793d0"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.aarch64-linux-musl.tar.gz"
[[spirv2clc]]
arch = "aarch64"
git-tree-sha1 = "e6fe415e1b3385cbe474b4c85c9d7d98bbd48531"
os = "freebsd"

    [[spirv2clc.download]]
    sha256 = "fed4948f4414453aaaf166b914e95c7a0ceeb0b8ea63f5ef34532b756dc2a62e"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.aarch64-unknown-freebsd.tar.gz"
[[spirv2clc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "871ee39e7f3c9854aa14d8e20be3dbf4f9e14ee9"
libc = "glibc"
os = "linux"

    [[spirv2clc.download]]
    sha256 = "4dbf220afd7b91d05a281b3f321e113908c8956269f2980c2d231474de873114"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.armv6l-linux-gnueabihf.tar.gz"
[[spirv2clc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c7908175228e3d3de05b3918f10599b697a07459"
libc = "musl"
os = "linux"

    [[spirv2clc.download]]
    sha256 = "acf5f7a0fbabfb770b6131dd92ecc3beb00074c005a63d74616432c40ceaaca9"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.armv6l-linux-musleabihf.tar.gz"
[[spirv2clc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b25f6b030ba68c5e5e0efddd357053ee6dd0ecd5"
libc = "glibc"
os = "linux"

    [[spirv2clc.download]]
    sha256 = "87df61fa45c1e81e0a964c2d978ec8530197fba456fbcae514ef8b0abbcabf77"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.armv7l-linux-gnueabihf.tar.gz"
[[spirv2clc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0ce1ae9a692a40758fec7718f0ef3ee9657c573e"
libc = "musl"
os = "linux"

    [[spirv2clc.download]]
    sha256 = "f4454a94b6a7bf871199b891cc9d05372b30e292db132ea35f1b1df76d7451c0"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.armv7l-linux-musleabihf.tar.gz"
[[spirv2clc]]
arch = "i686"
git-tree-sha1 = "d12d235d64f05252711d6ef85502b4379e04527b"
libc = "glibc"
os = "linux"

    [[spirv2clc.download]]
    sha256 = "610f40c3088c7c6cd1d4143a89c5b372ef1fc946f7ec6d4e11741d9025247ab8"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.i686-linux-gnu.tar.gz"
[[spirv2clc]]
arch = "i686"
git-tree-sha1 = "96b1eb005681cc4e29753986d5981ff45c012e48"
libc = "musl"
os = "linux"

    [[spirv2clc.download]]
    sha256 = "f963b4c3487680893a56d31dd26fa1e838059bb4caeecd99b38a161285aa1d40"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.i686-linux-musl.tar.gz"
[[spirv2clc]]
arch = "i686"
git-tree-sha1 = "5a9ddb619eced99f8c869e69ad37257068912ce4"
os = "windows"

    [[spirv2clc.download]]
    sha256 = "190ef9e1d05ef8ef660d392445041e99db28f9148a2b5041ecd9f8a0b63319f3"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.i686-w64-mingw32.tar.gz"
[[spirv2clc]]
arch = "powerpc64le"
git-tree-sha1 = "13b5a24f663a77c02fcb289c81c39dd2c18fbf76"
libc = "glibc"
os = "linux"

    [[spirv2clc.download]]
    sha256 = "915887388053e431538e302024a7b6adc1afb3f0cb096a8d87a06e67c00443f4"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.powerpc64le-linux-gnu.tar.gz"
[[spirv2clc]]
arch = "riscv64"
git-tree-sha1 = "14bfc3d1997200c8c4c30f2a3d4d2e1dd834d535"
libc = "glibc"
os = "linux"

    [[spirv2clc.download]]
    sha256 = "edba906dcdc0ee42aadd7c58b95853674d0846d1163c4e913d46aa45452a4a24"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.riscv64-linux-gnu.tar.gz"
[[spirv2clc]]
arch = "x86_64"
git-tree-sha1 = "d602805a2e1ae9686aee507627064144f62d4a32"
os = "macos"

    [[spirv2clc.download]]
    sha256 = "eab0c24595887091c4b2953471947da378873e0564d6ed1d5384ade7f49a3001"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.x86_64-apple-darwin.tar.gz"
[[spirv2clc]]
arch = "x86_64"
git-tree-sha1 = "3364447d0faa32ed8a4421c3519368916c2de223"
libc = "glibc"
os = "linux"

    [[spirv2clc.download]]
    sha256 = "46bc6a284de74300d7b0f6d32c4ab5f9253e7939ad10fe08a09d29c271732cf6"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.x86_64-linux-gnu.tar.gz"
[[spirv2clc]]
arch = "x86_64"
git-tree-sha1 = "395c18ad255f0fc552de7124e5d25b7193a87bf2"
libc = "musl"
os = "linux"

    [[spirv2clc.download]]
    sha256 = "2745b22e92e1b9ace11cd445e94f9b88f884b887038d9bf31394585e0034ef2c"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.x86_64-linux-musl.tar.gz"
[[spirv2clc]]
arch = "x86_64"
git-tree-sha1 = "e658a2578727ad7e0a3bd3cd1ec7539d6b539856"
os = "freebsd"

    [[spirv2clc.download]]
    sha256 = "73f0e6575aaf55445b7686372d55c3ebdae6ba5ece88b105043cd0e2da8886dc"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.x86_64-unknown-freebsd.tar.gz"
[[spirv2clc]]
arch = "x86_64"
git-tree-sha1 = "be6de3de257f5be578c818c7d17a33e8cd483859"
os = "windows"

    [[spirv2clc.download]]
    sha256 = "9c086305e8a117fb39bf53fb2141548cc61d2d9eee52bd45fed8b787b9d9a316"
    url = "https://github.com/JuliaBinaryWrappers/spirv2clc_jll.jl/releases/download/spirv2clc-v0.2.0+0/spirv2clc.v0.2.0.x86_64-w64-mingw32.tar.gz"
