# Autogenerated wrapper script for spirv2clc_jll for x86_64-unknown-freebsd
export spirv2clc

JLLWrappers.@generate_wrapper_header("spirv2clc")
JLLWrappers.@declare_executable_product(spirv2clc)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        spirv2clc,
        "bin/spirv2clc",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
